### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by NathanDunfield** [3-manifolds/SnapPy#112]
The first release candidate for Python 3.12 is now available and the final version is scheduled to be released on October 1, 2023.  We need to make SnapPy compatible, including the following binary components:

- [x] FXrays
- [x] low_index
- [x] knot_floer_homology
- [x] cypari
- [x] Spherogram
- [x] SnapPy itself

Depending on the module, this would also be a natural time to make sure everything works with Cython 3.0.  Note that `cibuildwheel` has started including Python 3.12 in the CI runs as of early August.

**Comment by NathanDunfield** [comment]
FYI: @culler, @unhyperbolic, @fchapoton

**Comment by culler** [comment]
With CyPari I encountered this error:
cypari/_pari.c:215168:26: error: no member named 'ob_digit' in 'struct
_longobject'

That would appear to be a change in the python api.

- Marc

**Comment by culler** [comment]
There was no issue with knot_floer_homology.

- Marc

**Comment by culler** [comment]
Ditto with Spherogram -- no build issues.

- Marc

**Comment by culler** [comment]
No issues with low_index or the manifold data.

- Marc

**Comment by NathanDunfield** [comment]
@culler Marc, thanks for getting started on this.  I kicked the CI for `FXrays` and `knot_floer_homology` and uploaded the resulting wheels to `pypi`.  I also pinned the version of `cibuildwheel` on those so it won't start springing new versions of Python on us in the future as in https://github.com/3-manifolds/Spherogram/pull/53.
